#!/bin/sh
set -e


# this will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; etc will work, but not arg1 arg2
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
    set -- varnish-agent -u root -g root -H /var/www/varnish-dashboard -c $AGENT_PORT -d -v "$@"
fi
sleep 1
exec "$@"