#!/bin/sh
set -e


# this will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; etc will work, but not arg1 arg2
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
    set -- varnishd -F -f /etc/varnish/default.vcl -a :80 -a :8443,PROXY -s malloc,$VARNISH_SIZE "$@"
fi

varnish-agent -u root -g root -n /var/lib/varnish/$(hostname) -c $AGENT_PORT
exec "$@"